[[redirects]]
  from = "/flex/airports/rest/v1/json/countryCode/*"
  to = "https://api.flightstats.com/flex/airports/rest/v1/json/countryCode/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
